---
image: ruby:3.1

cache:
  key: "$CI_COMMIT_REF_SLUG"
  paths:
    - vendor

stages:
  - build
  - test
  - deploy

build:
  stage: build
  before_script:
    - mkdir -p ~/bin
    - >-
      curl --proto '=https' --tlsv1.2 -sSf https://just.systems/install.sh
      | bash -s -- --to ~/bin
    - export PATH="$PATH:$HOME/bin"
    - git submodule sync
    - git submodule update --init
    - gem install bundler
    - bundle config set path 'vendor'
    - bundle config set without 'test'
    - bundle install
  script:
    - just build
  artifacts:
    paths:
      - adamliter.org
    name: "$CI_COMMIT_REF_SLUG"
    expire_in: 1 hour

test:
  stage: test
  before_script:
    - mkdir -p ~/bin
    - >-
      curl --proto '=https' --tlsv1.2 -sSf https://just.systems/install.sh
      | bash -s -- --to ~/bin
    - export PATH="$PATH:$HOME/bin"
    - gem install bundler
    - bundle config set path 'vendor'
    - bundle config set without 'development'
    - bundle install
    - "which locale-gen || (apt-get update -y && apt-get install locales -y)"
    - echo "en_US UTF-8" > /etc/locale.gen
    - locale-gen en_US.UTF-8
    - export LANG=en_US.UTF-8
    - export LANGUAGE=en_US.UTF-8
    - export LC_ALL=en_US.UTF-8
  script:
    - just proof

deploy:
  stage: deploy
  rules:
    - if: $CI_COMMIT_BRANCH == "main" && $CI_PROJECT_PATH == "adamliter/adamliter.org"
  before_script:
    - "which rsync || ( apt-get update -y && apt-get install rsync -y )"
    - "which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )"
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - mkdir -p ~/bin
    - >-
      curl --proto '=https' --tlsv1.2 -sSf https://just.systems/install.sh
      | bash -s -- --to ~/bin
    - export PATH="$PATH:$HOME/bin"
    - gem install bundler
    - bundle config set path 'vendor'
    - bundle config set without 'development test'
    - bundle install
  script:
    - just deploy-prod
